package salabaev.gekkolog.data.reminder

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import salabaev.gekkolog.data.gecko.Gecko

@Entity(tableName = "reminders",
    foreignKeys = [
        ForeignKey(
            entity = Gecko::class,
            parentColumns = ["id"],
            childColumns = ["geckoId"],
            onDelete = ForeignKey.CASCADE
        )
    ])
class Reminder {
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
    var date: Long? = null
    var geckoId: Int? = null
    var type: String? = null
    var description: String? = null
    var autoGenerated: Boolean? = null
}
